### PR TITLE
Fix game folder generation

### PR DESCRIPTION
**Pull request by wczhou5697**
Copy the current folder and filter out the modloader to the system temp folder, then move it into game folder.
By doing this the modloader executable and the game itself can share the same folder.

### CODE REVIEW

**Comment by AhhhSaturn** [comment]
what are the benefits of doing it this way? i cant seem to get it working on my machine and dont fully get the reason sorry

**Comment by wczhou5697** [comment]
by doing this the modloader and the moonstone island can share the same directory which is more intuitive to me or maybe the newcomer

**Comment by AhhhSaturn** [comment]
I've designed it to be in different folders so it can be fully independent from the original game, the users don't have to mess with the files just to play the vanilla game. while it's a good idea I don't think it's a good step for the loader

**Comment by wczhou5697** [comment]
I've never thought that way, maybe you are right but it feels so weird to me that create a folder for a mod loader in steam game library or maybe we can let the user specify where the game is as an option so it doesn't have to locate at steamapps/common directory

**Pull request closed without merging**
